function [C_D, C_L] = drag_and_lift_coiff(alpha, MAV)
    sigma_alpha = (1 + exp(-MAV.M*(alpha - MAV.alpha0)) + exp(MAV.M*(alpha + MAV.alpha0))) ...
                ./ ((1 + exp(-MAV.M*(alpha - MAV.alpha0))) .* (1 + exp(MAV.M*(alpha + MAV.alpha0))));

    C_L = (1 - sigma_alpha) * (MAV.C_L_0 + MAV.C_L_alpha * alpha) ...
            + sigma_alpha * (2 * sign(alpha) * (sin(alpha)^2) * cos(alpha));%sign
    C_D = (MAV.C_D_p + (MAV.C_L_0^2)/(pi*MAV.e*MAV.AR)) ...
        + (2*MAV.C_L_0*MAV.C_L_alpha)/(pi*MAV.e*MAV.AR) * alpha ...
        + (MAV.C_L_alpha^2)/(pi*MAV.e*MAV.AR) * alpha^2;
end